  version: '3'
    
  services:
    db:
      image: postgres:11.1
      container_name: db
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      image: django_drf:1
      container_name: django_drf-1
      ports:
        - "8001:8000"
      environment:
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASS=postgres
        - DB_HOST=db
      depends_on:
        - db